import test from'node:test';import assert from'node:assert/strict';import{Simulation,RULES}from'../src/simulation.js';
const advance=(s,n)=>{for(let i=0;i<n*60;i++)s.step(1/60);};
const bottle=(s,over={})=>Object.assign(s.addBottle(),{belt:'secondary',lane:2,x:0,z:0,up:false,defect:null,finicky:false},over);
test('dumper starts empty, loads deliberately, spills before full tilt, and holds angle',()=>{const s=new Simulation();assert.equal(s.loadBin(),true);advance(s,1.3);assert.equal(s.binLeft,s.binSize);s.setLift(1);advance(s,1.6);s.setLift(0);const tilt=s.tilt;advance(s,1);assert.ok(s.binLeft<s.binSize);assert.ok(tilt<100&&tilt>42);assert.equal(s.tilt,tilt);});
test('zero feeder leaves short belt still while the long belt keeps running',()=>{const s=new Simulation();s.setFeeder(0);const a=s.addBottle(),b=bottle(s),z=a.z,x=b.x;advance(s,1);assert.equal(a.z,z);assert.ok(b.x>x);});
test('stop cards pause only the long conveyor and expire in simulation time',()=>{const s=new Simulation();const b=bottle(s),p=s.addBottle(),z=p.z;s.stopBelt();advance(s,2);assert.equal(b.x,0);assert.ok(p.z>z);assert.equal(s.cards,0);assert.equal(s.stopBelt(),false);advance(s,6);assert.ok(b.x>0);});
test('standing an already upright bottle cannot farm points',()=>{const s=new Simulation();const b=bottle(s);s.action(b.id);const score=s.score;assert.equal(s.action(b.id),false);assert.equal(s.score,score);});
test('finicky bottles fall once; re-standing awards only recovery points',()=>{const s=new Simulation();const b=bottle(s,{finicky:true,wobbleAt:.1});s.action(b.id);advance(s,.2);assert.equal(b.up,false);const score=s.score;s.action(b.id);assert.equal(s.score-score,2);advance(s,.2);assert.equal(b.up,true);});
test('defect rejection earns points; rejecting good bottles loses points',()=>{const s=new Simulation();s.score=100;s.action(bottle(s,{defect:'cap'}).id,true);assert.equal(s.rejected,1);assert.equal(s.score,130);s.action(bottle(s).id,true);assert.equal(s.score,105);});
test('bad and fallen bottles cannot pass the machine for free',()=>{const s=new Simulation();bottle(s,{x:6,defect:'label',up:true});advance(s,2);assert.equal(s.waste,1);assert.equal(s.delivered,0);});
test('fullness ignores defects and fallen bottles; bonus requires upright good bottles',()=>{const s=new Simulation();for(let i=0;i<RULES.fullFlowAt;i++)bottle(s,{up:true,x:-4+Math.floor(i/5)*.6,lane:i%5,z:(i%5-2)*.48});advance(s,.1);assert.equal(s.fullFlow,true);assert.ok(s.score>=300);});
test('pause freezes timers, dumping, helpers and bonuses',()=>{const s=new Simulation();s.loadBin();s.paused=true;advance(s,10);assert.equal(s.time,0);assert.equal(s.loadTime,1.2);});
test('shift ends at 180 seconds, practice survives overflow',()=>{const s=new Simulation();advance(s,181);assert.equal(s.ended,true);assert.equal(s.time,180);const p=new Simulation({mode:'practice'});p.waste=20;advance(p,1);assert.equal(p.ended,false);});
test('same seed and actions reproduce the same bottles and result',()=>{const a=new Simulation({seed:73}),b=new Simulation({seed:73});for(const s of[a,b]){s.loadBin();advance(s,1.3);s.setLift(1);advance(s,10);}assert.deepEqual(a.bottles,b.bottles);assert.deepEqual(a.result(),b.result());});
test('clearing the juice freezes the clock for packing, then advances exactly once',()=>{const s=new Simulation();s.binsLoaded=s.binsRequired;s.batchDelivered=61;advance(s,.1);assert.equal(s.batchReady,true);assert.equal(s.level,1);const time=s.time;advance(s,30);assert.equal(s.time,time);assert.equal(s.loadBin(),false);assert.equal(s.stopBelt(),false);assert.equal(s.completeBatch(),true);assert.equal(s.completeBatch(),false);assert.equal(s.level,2);assert.equal(s.juice.name,'Celery + Lemon');assert.equal(s.score,300);assert.equal(s.batchDelivered,0);});

test('the final overflow freezes the exact saved result before later exits can add points',()=>{let result;const s=new Simulation({onEvent:e=>{if(e.type==='end')result=e.result;}});s.waste=11;bottle(s,{x:6,lane:0,defect:'cap',up:true,jam:1.5});bottle(s,{x:6,lane:1,up:true});s.step(1/60);assert.equal(s.ended,true);assert.deepEqual(s.result(),result);advance(s,2);assert.deepEqual(s.result(),result);});
