import{CompatibilityScene}from'./fallback.js';import{Simulation,RULES}from'./simulation.js';import{FactoryScene}from'./scene.js';import{AudioEngine}from'./audio.js';import{Community,friendlyError}from'./community.js';
const $=id=>document.getElementById(id),audio=new AudioEngine(),community=new Community();let mode='shift',playing=false,rejectMode=false,scene,sim,last=0,accumulator=0,eventTimer,runId,runOwner=null,pendingResult=null,challenge=null;let reduced=localStorage.getItem('sujaReducedFx')==='true'||matchMedia('(prefers-reduced-motion: reduce)').matches;
const query=new URLSearchParams(location.search),challengeCode=(query.get('challenge')||'').toUpperCase();
function notice(text){clearTimeout(eventTimer);$('event').textContent=text;$('event').hidden=false;eventTimer=setTimeout(()=>$('event').hidden=true,3200);}
function float(text,x,y){if(reduced)return;const n=document.createElement('span');n.className='float-score';n.textContent=text;n.style.left=x+'px';n.style.top=y+'px';$('floating').append(n);setTimeout(()=>n.remove(),850);}
function handleEvent(e){if(!playing)return;audio.play(e.type);if(e.type==='loaded')notice('Bin ready. Hold ↑ to begin tipping.');if(e.type==='binEmpty')notice(sim.binsLoaded<sim.binsRequired?'Bin empty — lower the dumper, then load again.':'Last bin! Clear the line for the next juice.');if(e.type==='mystery')notice('A little help? Open your purple ? bonus.');if(e.type==='reward'){const labels={stop:'Line stopped · 8 seconds',helper:'Extra hands · 25 seconds',points:'+250 bonus points',card:'One stop card added',quality:'Quality sweep · 18 seconds'};notice(labels[e.kind]);}if(e.type==='waste')notice(e.why==='defect'?'Bad bottle reached the machine · −60':'Bottle lost · −35');if(e.type==='fullFlow')notice('FULL FLOW! Triple points for 10 seconds');if(e.type==='level')notice(`Juice ${e.level}: ${e.juice} · +300`);if(e.type==='wobble')notice('Bottle down! Check downstream.');if(e.type==='stand'&&!reduced)scene.burst(e.x,e.z);if(e.type==='end')endRun(e.result);}
function pick(id,right,x,y){if(!playing||sim.paused)return;const before=sim.score;if(sim.action(id,right||rejectMode))float((sim.score>=before?'+':'')+(sim.score-before),x,y);}
function createDemo(){sim=new Simulation({mode:'practice'});for(let i=0;i<29;i++){const b=sim.addBottle();b.belt='secondary';b.x=-3.8+Math.floor(i/5)*1.25;b.lane=i%5;b.z=(b.lane-2)*.48;b.up=i%4!==0;}sim.paused=true;}
try{scene=new FactoryScene($('world'),pick);}catch(e){console.warn('3D unavailable; using compatibility view.',e.message);const old=$('world'),replacement=old.cloneNode(false);old.replaceWith(replacement);scene=new CompatibilityScene(replacement,pick);$('view').textContent='Overhead';$('view').disabled=true;}
createDemo();requestAnimationFrame(frame);

function frame(now){const dt=Math.min(.08,(now-(last||now))/1000);last=now;if(playing){accumulator+=dt;while(accumulator>=1/60){sim.step(1/60);accumulator-=1/60;}updateHud();}scene.render(sim,dt||.016);requestAnimationFrame(frame);}
function updateHud(){
 $('score').textContent=sim.score.toLocaleString();$('combo').textContent=sim.combo>=2?`${sim.combo} in a row · ×${Math.min(4,1+Math.floor(sim.combo/8))}`:'Build your streak';const seconds=mode==='shift'?Math.ceil(RULES.shiftSeconds-sim.time):Math.floor(sim.time);$('timer').textContent=mode==='practice'?'PRACTICE':`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;$('juice').textContent=sim.juice.name;$('level').textContent=`JUICE ${String(sim.level).padStart(2,'0')}`;$('waste').textContent=mode==='practice'?`${sim.waste} lost`:`${sim.waste} / ${RULES.wasteLimit} lost`;$('flow-fill').style.width=sim.fullness*100+'%';$('flow-label').textContent=sim.fullFlow?`FULL FLOW · ${Math.ceil(sim.fullUntil-sim.time)}s · ×3`:`${Math.round(sim.fullness*100)}% upright fullness`;document.body.classList.toggle('full-flow',sim.fullFlow);$('tilt-label').textContent=`Tilt ${Math.round(sim.tilt)}°`;$('bin-left').textContent=sim.binState==='loading'?'Loading…':sim.binLeft?`${sim.binLeft} bottles left`:'Bin empty';$('bin-counter').textContent=`BIN ${sim.binsLoaded} / ${sim.binsRequired}`;$('load').disabled=sim.binState!=='empty'||sim.tilt>8||sim.binsLoaded>=sim.binsRequired;$('stop-belt').disabled=!sim.cards;$('stop-belt').textContent=sim.stopped?`Stopped ${Math.ceil(sim.stopUntil-sim.time)}s`:`Stop ×${sim.cards}`;$('mystery').hidden=!sim.pendingReward;
 const statuses=[];if(sim.helpers.length)statuses.push(`${sim.helpers.length} helper${sim.helpers.length===1?'':'s'} · ${Math.ceil(Math.max(...sim.helpers.map(h=>h.until))-sim.time)}s`);if(sim.qualityUntil>sim.time)statuses.push('Quality sweep');if(sim.stopped)statuses.push('Long belt stopped');$('bonus-status').textContent=statuses.join(' · ');$('bonus-status').hidden=!statuses.length;
 let hint='Tap fallen bottles · Reject missing labels, bad caps & low fills';if(!sim.binsLoaded)hint='① Load a bin to begin.';else if(sim.binState==='loading')hint='Pallet jack moving the bin into position…';else if(sim.binLeft&&sim.tilt<43)hint='Hold ↑ past 42° to pour. Release to hold the angle.';else if(!sim.binLeft&&sim.binsLoaded<sim.binsRequired)hint=sim.tilt>8?'Hold ↓ to lower the empty bin.':'Load your next bin.';else if(sim.bottles.filter(b=>b.belt==='primary').length>25)hint='Feeder getting crowded — ease the dumper down.';else if(sim.pressure>1)hint='Transfer is packed! Stand bottles near the left end.';$('hint').textContent=hint;
}
async function start(){if(!scene)return;if(challengeCode&&(!challenge||challenge.status!=='open')){notice('This challenge is not open yet. Return to Game Center.');return;}await audio.unlock();audio.active=true;mode=challengeCode?'shift':mode;const seed=challenge?challenge.seed:Number(new Date().toISOString().slice(0,10).replaceAll('-',''));sim=new Simulation({mode,seed,onEvent:handleEvent});playing=true;accumulator=0;runId=crypto.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint8Array(16)),v=>v.toString(16).padStart(2,'0')).join('');runOwner=community.profile?.profileId||null;pendingResult=null;rejectMode=false;setReject(false);$('speed').value=50;$('speed-value').textContent='50%';$('menu').hidden=true;for(const id of['hud','controls','pause','hint'])$(id).hidden=false;for(const d of document.querySelectorAll('dialog'))if(d.open)d.close();scene.startIntro();}
function setReject(value){rejectMode=value;$('stand-mode').classList.toggle('selected',!value);$('reject-mode').classList.toggle('selected',value);$('stand-mode').setAttribute('aria-pressed',String(!value));$('reject-mode').setAttribute('aria-pressed',String(value));$('world').style.cursor=value?'crosshair':'pointer';}
function pause(){if(!playing||sim.ended)return;sim.paused=true;sim.setLift(0);audio.active=false;if(!$('pause-dialog').open)$('pause-dialog').showModal();}
function resume(){if(!playing||sim.ended)return;sim.paused=false;audio.active=true;$('pause-dialog').close();audio.unlock();}
function menu(){playing=false;audio.active=false;for(const d of document.querySelectorAll('dialog'))d.close();for(const id of['hud','controls','pause','hint','mystery','event','bonus-status'])$(id).hidden=true;$('menu').hidden=false;document.body.classList.remove('full-flow');createDemo();}
function endRun(result){audio.active=false;pendingResult=result;sim.paused=true;$('result-reason').textContent=result.reason.toUpperCase();$('result-score').textContent=result.score.toLocaleString();$('result-grid').replaceChildren();for(const[label,value]of[['Stood up',result.stood],['Good exits',result.delivered],['Defects caught',result.rejected],['Best combo',result.maxCombo],['Juice level',result.level],['Fullness',result.bestFullness+'%']]){const n=document.createElement('div'),b=document.createElement('b'),s=document.createElement('span');b.textContent=value;s.textContent=label;n.append(b,s);$('result-grid').append(n);}$('results-dialog').showModal();saveResult();}
async function saveResult(){if(!pendingResult)return;$('retry-save').hidden=true;if(mode==='practice'){$('save-status').textContent='Practice complete. Practice scores are not ranked.';return;}if(!runOwner){$('save-status').textContent='Guest run. Sign in before your next shift to save your score.';return;}if(community.profile?.profileId!==runOwner){$('save-status').textContent='Your player changed. This run cannot be saved to a different account.';return;}$('save-status').textContent='Saving your shift…';try{await community.saveRun(runId,pendingResult,challengeCode);$('save-status').textContent='Shift saved to your player card and Hall of Fame.';}catch(e){$('save-status').textContent=friendlyError(e);$('retry-save').hidden=false;}}
$('retry-save').addEventListener('click',saveResult);$('start').addEventListener('click',start);$('again').addEventListener('click',start);$('restart').addEventListener('click',start);$('resume').addEventListener('click',resume);$('pause').addEventListener('click',pause);$('quit').addEventListener('click',menu);$('result-menu').addEventListener('click',menu);$('load').addEventListener('click',()=>sim.loadBin());$('stop-belt').addEventListener('click',()=>sim.stopBelt());$('mystery').addEventListener('click',()=>sim.openReward());$('stand-mode').addEventListener('click',()=>setReject(false));$('reject-mode').addEventListener('click',()=>setReject(!rejectMode));$('speed').addEventListener('input',e=>{sim.setFeeder(e.target.value/100);$('speed-value').textContent=e.target.value+'%';});
for(const[id,dir]of[['raise',1],['lower',-1]]){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(playing&&!sim.paused)sim.setLift(dir);});for(const event of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>sim.setLift(0));}
function toggleView(){if($('view').disabled)return;scene.setView(scene.view==='first'?'overhead':'first');$('view').textContent=scene.view==='first'?'Overhead':'First person';}
$('view').addEventListener('click',toggleView);for(const b of document.querySelectorAll('[data-mode]'))b.addEventListener('click',()=>{mode=b.dataset.mode;for(const x of document.querySelectorAll('[data-mode]'))x.classList.toggle('selected',x===b);});
for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>$(b.dataset.close).close());$('how').addEventListener('click',()=>$('help-dialog').showModal());$('sound').addEventListener('click',()=>{if(playing&&!sim.ended)pause();$('sound-dialog').showModal();audio.unlock();});for(const[k,id]of[['music','music-volume'],['sfx','sfx-volume']]){$(id).value=audio[k]*100;$(id).addEventListener('input',e=>{audio.set(k,e.target.value/100);audio.unlock();});}$('reduced-fx').checked=reduced;$('reduced-fx').addEventListener('change',e=>{reduced=e.target.checked;localStorage.setItem('sujaReducedFx',String(reduced));});
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='Escape'&&playing&&!sim.ended){e.preventDefault();sim.paused?resume():pause();return;}if(document.querySelector('dialog[open]'))return;if(e.key.toLowerCase()==='v')toggleView();if(!playing||sim.paused||sim.ended)return;if(['ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.repeat)return;if(e.key==='ArrowUp')sim.setLift(1);if(e.key==='ArrowDown')sim.setLift(-1);if(e.key.toLowerCase()==='l')sim.loadBin();if(e.key.toLowerCase()==='r')setReject(!rejectMode);if(e.key===' ')sim.stopBelt();});window.addEventListener('keyup',e=>{if(['ArrowUp','ArrowDown'].includes(e.key))sim.setLift(0);});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',()=>{sim?.setLift(0);if(playing)pause();});$('pause-dialog').addEventListener('cancel',e=>{e.preventDefault();resume();});$('results-dialog').addEventListener('cancel',e=>{e.preventDefault();menu();});
community.subscribe(p=>{$('player-status').textContent=p?`Playing as ${p.displayName} · Your competitive shifts save to SUJA.`:'Guest play · Sign in at SUJA Game Center to save scores.';});community.init().then(async()=>{if(challengeCode){$('challenge-status').hidden=false;$('challenge-status').textContent='Connecting to challenge…';try{challenge=await community.read(`challenges/${challengeCode}`);if(!challenge)throw new Error('Challenge not found.');$('challenge-status').textContent=`${challenge.title} · Hosted by ${challenge.hostName} · ${challenge.status}`;document.querySelector('.mode-picker').hidden=true;$('start').disabled=challenge.status!=='open';community.watch(`challenges/${challengeCode}`,c=>{challenge=c;$('start').disabled=!c||c.status!=='open';$('challenge-status').textContent=c?`${c.title} · ${c.status}`:'Challenge unavailable';});}catch(e){$('challenge-status').textContent=friendlyError(e);$('start').disabled=true;}}}).catch(()=>{$('player-status').textContent='Community connection unavailable. Guest play is ready.';});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
// Debug snapshots are opt-in, read-only, and contain no identity or score-writing controls.
if(query.get('debug')==='1')window.bottlesDebug={snapshot:()=>({...sim.result(),bottles:sim.bottles.map(b=>({...b})),tilt:sim.tilt,binLeft:sim.binLeft,binState:sim.binState,feeder:sim.feeder}),project:(id)=>{if(scene.project)return scene.project(id);const m=scene.meshes.get(id);if(!m)return null;const p=m.position.clone();p.y+=.4;p.project(scene.camera);const r=$('world').getBoundingClientRect();return{x:r.x+(p.x+1)*r.width/2,y:r.y+(-p.y+1)*r.height/2};}};
